### ISSUE TITLE
Plugin with id 'cz.habarta.typescript-generator' not found

### ISSUE THREAD

**Issue by mobratil** [vojtechhabarta/typescript-generator#139]
Hi,

I have following problem. When I run `gradle build` command, it returns error with message:
`Plugin with id 'cz.habarta.typescript-generator' not found.`

Here is my gradle.build:
```
apply plugin: 'java'
apply plugin: 'cz.habarta.typescript-generator'

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath group: 'cz.habarta.typescript-generator', name: 'typescript-generator', version: '1.24.317'
    }
}
generateTypeScript {
    jsonLibrary = 'jackson2'
    classes = [

    ]
    outputFile = 'build/messages.d.ts'
    outputKind = 'global'
    namespace = 'Rest'
}
```

Do you know what wen wrong?

Thank you.

Martin Obrátil

**Comment by vojtechhabarta** [comment]
Hi / Ahoj,

I don't know what might be wrong since I don't use Gradle. It should not be a problem with typescript-generator itself, it is probably some general Gradle configuration issue.

Try to compare your configuration with this sample: https://github.com/vojtechhabarta/typescript-generator/blob/master/sample-gradle/build.gradle. I would try to add following snippet to top level:
``` groovy
repositories {
    mavenCentral()
}
```

Anybody else can help?

**Comment by mobratil** [comment]
Thanks / Děkuji

I put code snippet you posted, but still no luck :-(

**Comment by mobratil** [comment]
I found the problem. I had wrong definition in `dependencies`. Correct one is this: 

```classpath group: 'cz.habarta.typescript-generator', name: 'typescript-generator-gradle-plugin', version: '1.24.317'```

instead of this:

```classpath group: 'cz.habarta.typescript-generator', name: 'typescript-generator', version: '1.24.317'```

**Comment by vojtechhabarta** [comment]
Great to see that you solved the problem 😄
