### ISSUE TITLE
How can I call this from an ANT task?

### ISSUE THREAD

**Issue by alshain** [vojtechhabarta/typescript-generator#145]
Is it possible to call this from an ANT task?

**Comment by vojtechhabarta** [comment]
Currently there is no special support for Ant in typescript-generator. It can be used from Maven, Gradle or invoked from Java directly.

Should typescript-generator implement `org.apache.tools.ant.Task`?
If yes, it should be in separate module `typescript-generator-ant-task` (like plugins for Maven and Gradle).

If there is demand for this feature it could be added to typescript-generator. Since I don't use Ant I would prefer if somebody who is actually using it could implement the support. Anybody interested?

**Comment by vojtechhabarta** [comment]
Closing issues/PRs after [v2 release](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.0.400).

Ant is not much used now so I personally don't want to implement Ant task.
But contribution is welcome.
