### ISSUE TITLE
Deterministic ordering of discriminants

### ISSUE THREAD

**Issue by glentakahashi** [vojtechhabarta/typescript-generator#156]
@sayresVT and @vojtechhabarta for feedback.

I propose two options for making discriminants' ordering more consistent:
1) https://github.com/vojtechhabarta/typescript-generator/pull/152 will sort discriminants by the tagged union of the first matching parent class. I prefer this, but was unsure on how technically correct my code was. Tried thinking through edge cases, and it seemed to work for all of them.
2) https://github.com/vojtechhabarta/typescript-generator/pull/155 optionally sorts discriminants alphabetically. Main "downside" is that the ordering will differ from tagged unions and jsonsubtypes, which probably isn't as big of an issue?

thoughts on 1 or 2?

**Comment by vojtechhabarta** [comment]
I will close this issue and associated PRs because it seems that it is not a big problem to not have stable order of these discriminants. It produces diff in source control only rarely (and is relevant only when people put generated output in source control).

Many thanks @glentakahashi for exploring and implementing these two solutions. We can revive this issue if situation changes sometime in the future.
