### ISSUE TITLE
Order of exports

### ISSUE THREAD

**Issue by courado** [vojtechhabarta/typescript-generator#157]
I noticed that having two classes named `MyClass` and `ZAbstract` where `MyClass extends Abstract` then the generated typescript is :

```ts
// Generated using typescript-generator version 1.27.339 on 2017-06-29 19:54:01.

export interface MyClass extends ZAbstract {
}

export interface ZAbstract {
}

```

This hits an error in typescript transpiler : `Class 'ZAbstract' used before its declaration`

The plugin configuration is 

```xml
<plugin>
    <groupId>cz.habarta.typescript-generator</groupId>
    <artifactId>typescript-generator-maven-plugin</artifactId>
    <version>1.27.339</version>
    <executions>
        <execution>
            <id>generate</id>
            <goals>
                <goal>generate</goal>
            </goals>
            <configuration>
                <jsonLibrary>jackson2</jsonLibrary>
                <classPatterns>
                    <pattern>my.domain.*</pattern>
                </classPatterns>
                <outputFile>target/sample.d.ts</outputFile>
                <outputKind>module</outputKind>
            </configuration>
        </execution>
    </executions>
</plugin>
```

**Comment by vojtechhabarta** [comment]
Generated output is correct. **Interfaces** can be ordered arbitrary.

However base **class** must occur before derived class. How do you generate classes? Ideally you should fix that tool but if this is not possible typescript-generator have some options which can help you:
- Java classes can be specified individually in required order
- instead of interfaces it is possible to generate classes (and eliminate your tool which doesn't order classes correctly)

How exactly your build pipeline looks like?

**Comment by courado** [comment]
Well, your tool is really powerful.
I was parsing the ts with Python and forgot about the ordering (I thought interfaces have to be ordered)

This configuration fixed it for me (eliminating my tool)
```xml
<configuration>
    <outputFileType>implementationFile</outputFileType>
    <mapEnum>asEnum</mapEnum>
    <mapClasses>asClasses</mapClasses>
</configuration>
```

Thanks !

**Comment by vojtechhabarta** [comment]
Great to see that it works for you, thanks.
