### ISSUE TITLE
generated properties order changes between generations

### ISSUE THREAD

**Issue by cluelessjoe** [vojtechhabarta/typescript-generator#160]
Hi

I'm generating the TS from a class in src/test/java through a main() method and from some junit test (to make sure the pojo were all generated in typescript).

I've an interface which is generated in TS and when generating from a main or from junit the attributes order changes.

The generation code I use is 
``` java
Settings settings = new Settings();
settings.jsonLibrary = JsonLibrary.jackson2;
settings.setStringQuotes(StringQuotes.singleQuotes);
settings.outputKind = TypeScriptOutputKind.module;
settings.outputFileType = TypeScriptFileType.implementationFile;
settings.mapClasses = ClassMapping.asClasses;
settings.declarePropertiesAsReadOnly = true;
settings.customTypeMappings.put("java.time.ZonedDateTime", "string");

Input input = Input.fromClassNamesAndJaxrsApplication(
        Collections.emptyList(),
        Arrays.asList("com.foo.project.common.**Rest"),
        null,
        false,
        settings.getExcludeFilter(),
        (URLClassLoader) this.getClass().getClassLoader(),
        false);
new TypeScriptGenerator(settings)
        .generateTypeScript(
                input,
                Output.to(output));
```

And my interface refers to other generated types like this:
``` java
public interface PersonSummary {

    String getId();
    String getName();
    PersonRest.Gender getGender();
    ReferentRest getReferent();
}
```

Depending on whether I run from main or JUnit, the gender attribute position changes in the generated ts file.

Is it normal? Could I make it stay at the same position?

Thanks again for typescript-generator !

**Comment by vojtechhabarta** [comment]
I think this is caused by the fact that Java reflections doesn't return methods in original order (methods are stored in some hash map). From my experience when I use public fields instead of getters then properties are always in original order.

Typescript-generator uses Jackson2 to get list of properties and I think Jackson has some heuristic how to preserve original order. You can try to add corresponding fields in addition to getters. Or you can google how Jackson handles this issue.

You can also set `sortDeclarations` parameter to `true` which sorts declarations (types, properties) alphabetically.

**Comment by cluelessjoe** [comment]
Thanks a lot for your quick answer. I've an interface on the Java side too, thus using public final attributes doesn't help.
I'll look into jackson :)
