### ISSUE TITLE
Generating TS classes with constructor?

### ISSUE THREAD

**Issue by cluelessjoe** [vojtechhabarta/typescript-generator#162]
Hi

Currently a java class transpiled with the following settings ends up without constructor in the TS file, which makes creating new instances, in TS, through new Foo() impossible.

Settings:
```
settings.outputKind = TypeScriptOutputKind.module;
settings.outputFileType = TypeScriptFileType.implementationFile;
settings.mapClasses = ClassMapping.asClasses;
settings.declarePropertiesAsReadOnly = true;
```
Example of a generated TS class:
```
export class Foo {
    readonly id: string;
    readonly bar: string;
}
```
This allows only
```
const foo:Foo={'id':'foo', 'bar':"bar"};
```
Example of the same class with a constructor
```
export class Foo {
	constructor(readonly id: string,readonly bar: string){}
}
```
this would allow on top of the previous creation:
```
const foo:Foo=new Foo("id","bar");
```

Would it be possible?

Thanks again for typescript-generator!

**Comment by vojtechhabarta** [comment]
@cluelessjoe sorry for late response.

I think generating constructor parameter properties has some drawbacks.

Properties in Java doesn't have **guaranteed order** so once we could have
`constructor(readonly id: string, readonly bar: string) {}`
and after some change in class source we could have
`constructor(readonly bar: string, readonly id: string) {}`
which would break user code.

**Sorting** properties **alphabetically** is also problematic: renaming could change order too.

Changing **required** property to **optional** and vice versa requires reordering because optional parameters must appear after all required parameters. So again the same problem.

So I think this feature would created many compatibility problems in future versions of user codebases. Some of them could be caught by TypeScript compiler but some couldn't like `id` <-> `bar` strings exchange.

**Comment by JosephBL** [comment]
Then for the reply :) Many issues there indeed. A pity it would be have been more concise :'(

Thanks again!

**Comment by cluelessjoe** [comment]
Thanks for the reply :) Many issues there indeed, got it. A pity though :(

Thanks again!
