### ISSUE TITLE
Map java annotations to typescript decorators

### ISSUE THREAD

**Issue by spetsdyn** [vojtechhabarta/typescript-generator#164]
Add functionality for mapping java annotations to typescript decorators or at least parse the java annotations and map them to some model.

**Comment by vojtechhabarta** [comment]
@spetsdyn sorry for late response. Model for Java annotations would be rather complex with all allowed value types, default values, inheritance... Or do you need just annotations without values?

What is your use case for this feature? Maybe we could implement solution specifically for this use case.

**Comment by noguespi** [comment]
Well that's a very interesting feature I was thinking about too.

I do server side validation on some request which are simple POJO annotated with javax.validation annotations.

If I could export the annotation name to a typescript decorator, I could  probably client side validation automatically too.

By example : 
```java
class Request {
@Email
String email;
}
```
would translate to : 
```typescript
    export class Request {
        @Email()
        buyerId: string
    }
```

or we could do more complex mapping by reusing customTypeMappings configuration option.

**Comment by vojtechhabarta** [comment]
The problem is to decide what exactly should be supported. @noguespi your example is just annotation without any parameters but example @spetsdyn wrote has single number parameter. So which types should be supported? And should we generate TypeScript decorators for all used Java annotations or should we try to reuse some library (custom or public if there is any)?

This feature could be useful but I would wait because ECMAScript decorators proposal is still in early stage and I am not sure what will happen to decorators TypeScript has today.

**Comment by yutou527** [comment]
/**
* like this
*/
i just want to support the static annotations, 
but , anyway , this is a awsome project 👍

**Comment by vojtechhabarta** [comment]
@yutou527 do you mean Java annotations like `@Nullable` or do you mean JavaDoc comments?
JavaDoc comments are supported but first it is needed to extract these comments to XML file using javadoc tool. I can help you with it.

**Comment by yutou527** [comment]
@vojtechhabarta   
found it !
https://github.com/vojtechhabarta/typescript-generator/wiki/Javadoc
thanks!

**Comment by malakeel** [comment]
I know this issue is closed. Is there any possibility this can be reconsidered  ?
