### ISSUE TITLE
Is there a way to mark all inherited fields as 'optional' ?

### ISSUE THREAD

**Issue by emreavsar** [vojtechhabarta/typescript-generator#180]
Let's assume I'm extending a class from a library, and I'm interested only in exporting exactly the extensions of my class to typescript because there is already a typescript typing for the library classes. How is this possible?

Scenario:
```
public class MyExtension extends LibraryClassA {
  private String myString;
  // some inherited fields from LibraryClassA
}
```

-> This should turn into something like:

```
declare namespace mynamespace {
    interface MyExtension extends LibraryClassA {
        myString: string;
        // no inherited fields, since they are already in the extended interface.
    }
}
```

Is there a way for this? Is this a common use-case? Should I go for this or not?

The reason why I'm asking: the LibraryClassA has like 20 attributes, and I cannot change the LibraryClassA... And I don't want to create my variables in typescript like:

```
const myExtensionInstance: mynamespace.MyExtension = {
    myString: 'hello world',
    inheritedField1: null,
    inheritedField2: null,
    inheritedField3: null,
    inheritedField4: null,
    inheritedField5: null,
    // ... <- set all inherited fields to null
}
```

**Comment by vojtechhabarta** [comment]
If you do not need inherited properties at all you can try this:
1. exclude `LibraryClassA` in configuration using `excludeClasses` parameter
2. turn off all auto-detected properties using `@JsonAutoDetect` annotation
3. explicitly include all your properties using `@JsonProperty` annotation
Example:
``` java
@JsonAutoDetect(
        creatorVisibility = JsonAutoDetect.Visibility.NONE,
        fieldVisibility = JsonAutoDetect.Visibility.NONE,
        getterVisibility = JsonAutoDetect.Visibility.NONE,
        isGetterVisibility = JsonAutoDetect.Visibility.NONE,
        setterVisibility = JsonAutoDetect.Visibility.NONE
)
public class MyExtension extends LibraryClassA {
    @JsonProperty
    public String myString;
}
```

Of course this have some disadvantages. Or does it work for you?

**Comment by emreavsar** [comment]
That's almost what I want, but now I'm getting only this:
```
declare namespace mynamespace {
    interface MyExtension {
        myString: string;
    }
}
```

What I need extra is (`extends LibraryClassA`) like this:
```
declare namespace mynamespace {
    interface MyExtension extends LibraryClassA {
        myString: string;
        // no inherited fields, since they are already in the extended interface.
    }
}
```

**Comment by vojtechhabarta** [comment]
Why do you need `extends LibraryClassA`? If you do not need inherited properties I thing you also do not need `extends` because TypeScript has structural typing. But if you want to have inherited (optional) properties that's harder. 

It is not possible to have different configurations for different classes. Since parent class in not "yours" you can try to configure typescript-generator that it generates properties as optional by default and explicitly mark your properties as required. This can be achieved using new configuration parameter `optionalProperties` with value `useLibraryDefinition`. This uses Jackson2 to determine if property should be optional or required. I assume that properties in your parent class don't have Jackson2 annotations so they will be optional. Then you can annotate your properties with `@JsonProperty(required = true)`. See #183.
