### ISSUE TITLE
One output file for each class pattern

### ISSUE THREAD

**Issue by fplini** [vojtechhabarta/typescript-generator#199]
Hi all, 
my outputFile are going to be too big and I want to know if is there a way to generate 1 output file (.ts) for each class pattern?

Then.. is there a way to exclude a class by type? 
Ex. I want to exclude all enum class inside a package.

Thanks all
Fabrizio

**Comment by vojtechhabarta** [comment]
Hi Fabrizio,
- generate multiple output files is not possible and I don't want to add it because it would add complexity with combination of global/namespace/module variants.
- exclude classes is possible, you can use `excludeClasses` or `excludeClassPatterns` (which supports wildcards) - see [Configuration parameters](http://www.habarta.cz/typescript-generator/maven/typescript-generator-maven-plugin/generate-mojo.html) and also [Class Names Glob Patterns](https://github.com/vojtechhabarta/typescript-generator/wiki/Class-Names-Glob-Patterns) wiki page.
