### ISSUE TITLE
Feature Suggestion: customTypeNamingFunction with third parameter "isProperty"

### ISSUE THREAD

**Issue by Q-Man** [vojtechhabarta/typescript-generator#217]
I'm using the typescript generator in a project where some properties of the generated JSON can contain an object or a string which represents a URL where the actual object can be loaded lazy by a rest service.

For that I want to use the customTypeNamingFunction like this:

```
function(name, simpleName) {
	if (name.startsWith('com.potentiallylazy.')) return simpleName + ' | string'; 
}
```

So all Properties of the package `com.potentiallylazy` would be generated as the Class itself or string and the client knows that he has to check this.

If I use this example with a class `com.potentiallylazy.LazyClass` I see the property generated as possible string, that's what I want:
```
export interface MyClass {
    lazy: LazyClass | string;
}
```

But I also see the ` | string` suffix generated in the definition of LazyClass what breaks the code:

```
export interface LazyClass | string {
}
```

To distinguish these 2 cases it would be great if the customTypeNamingFunction got a third boolean parameter "isProperty". Then I could do this:

```
function(name, simpleName, isProperty) {
	if (isProperty && name.startsWith('com.potentiallylazy.')) return simpleName + ' | string'; 
}
```

Or is there another way to achieve what I want?

**Comment by vojtechhabarta** [comment]
Currently there is no way to do this. `customTypeNamingFunction` parameter is really just for naming not for types.

I have some idea how to do this with [_mapped types_](https://www.typescriptlang.org/docs/handbook/advanced-types.html#mapped-types) and [_conditional types_](https://github.com/Microsoft/TypeScript/pull/21316) in TypeScript. (Conditional types are planned for TypeScript 2.8.)

Taking your example we would generate interface for `MyClass` as usual and then you could create mapped type from it where you would add `| string` to lazy properties.

First you would need some marker to mark classes which are potentially lazy:
``` typescript
interface PotentiallyLazy {
    _potentiallyLazy: any;
}
```

Then you could create `LazyProperties` generic type like this:
``` typescript
type LazyProperties<T> = {
    [P in keyof T]: T[P] extends PotentiallyLazy ? T[P] | string : T[P];
}
```

This `LazyProperties` type takes some type, goes through its properties and if property is `PotentiallyLazy` it adds `| string` to its type. Otherwise it leaves property type as it is.

So continuing with your example this would be generated:
``` typescript
interface LazyClass extends PotentiallyLazy {
}

interface EagerClass {
}

interface MyClass {
    lazy: LazyClass;
    eager: EagerClass;
}
```

And then you could use it like this:
``` typescript
declare const myClass: MyClass;
const lazyMyClass = myClass as LazyProperties<MyClass>;
const lazyClass = lazyMyClass.lazy;    // string | LazyClass
const eagerClass = lazyMyClass.eager;  // EagerClass
```

Downside is that `myClass` needs to be casted to `LazyProperties<MyClass>`.
Advantage is that you could use both variants of `MyClass`, for example for sending data you would use original type and for received data you would use mapped type like this:
``` typescript
interface Client {
    updateMyClass(myClass: MyClass): LazyProperties<MyClass>;
}
```

**Comment by Q-Man** [comment]
Thank you very much for the inspiration, I wasn't aware that conditional types are planned for TypeScript. This will solve the problem.

**Comment by vojtechhabarta** [comment]
TypeScript 2.8 is released, closing the issue.
