### ISSUE TITLE
(from java8->10) ClassLoaders$AppClassLoader cannot be cast to URLClassLoader 

### ISSUE THREAD

**Issue by istiti** [vojtechhabarta/typescript-generator#231]
Hi @vojtechhabarta 
In java8 I had this code to programatically generate ts files : 
`Input input = Input.fromClassNamesAndJaxrsApplication(null, sett.mapClassesAsClassesPatterns, null, false,  sett.getExcludeFilter(),  (URLClassLoader) SpringBootApplicationLauncher.class.getClassLoader(), false);`

After updating to java10 I get exception 
`Exception in thread "main" java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader at thurnherr.immob10web.SpringBootApplicationLauncher.main(SpringBootApplicationLauncher.java:131)`

I wonder if im using `fromClassNamesAndJaxrsApplication()` method in right way.

Thanks

**Comment by istiti** [comment]
fuxed by using `URLClassLoader loader = new URLClassLoader(path, SpringBootApplicationLauncher.class.getClassLoader());` donno if its right way but it works

**Comment by vojtechhabarta** [comment]
Hi @istiti,

`Input.fromClassNamesAndJaxrsApplication` requires `URLClassLoader` (and not arbitrary `ClassLoader`) because it uses its URLs for class-path scanning. I am not sure if I could easily change the class-path scanning so that it works well with any `ClassLoader`.

So it is great to hear you solved it.
