### ISSUE TITLE
Namespace per file pattern

### ISSUE THREAD

**Issue by rhandersen** [vojtechhabarta/typescript-generator#254]
Hi,

First of all, thank you for a very useful tool!

I have two different file patterns, and would like to generate a namespace for each of them. 

Can you recommend a good way of achieving this? I am using Gradle, and I'm not quite sure what would be the best way to do this. 

Thanks in advance!

**Comment by vojtechhabarta** [comment]
Hi, thanks for your interest in typescript-generator.

Actually generating namespaces for file patterns is not possible. (It is only possible to have one namespace for all declarations or to map all Java packages to namespaces.)

You can try to run typescript-generator separately for these two patterns but you will probably end up with most of the declarations from first run duplicated in second run (which should not be a problem for TypeScript but definitely it is not good).

I am thinking about achieving something similar with modules in some future version but not with namespaces since modules seems to be generally preferred way nowadays.

**Comment by vojtechhabarta** [comment]
If you would like to generate two modules instead of two namespaces you could try to use new typescript-generator feature #276. Examples in description are for Maven but they maps directly to Gradle and I can, of course, help you.

**Comment by vojtechhabarta** [comment]
Hopefully you can live with single namespace or you can use [dependent modules](https://github.com/vojtechhabarta/typescript-generator/pull/276) feature.
