### ISSUE TITLE
Setting initial values

### ISSUE THREAD

**Issue by thepian** [vojtechhabarta/typescript-generator#258]
Have you thought of a way to generate classes with initial values?

Does Jackson have anything?

```
class Generated {
  value = true;
  value2 = 'abc';
}
```

**Comment by vojtechhabarta** [comment]
Jackson just instantiates a class so if you initialize field in its declaration (or in constructor) this value is used as default value.

I am not sure if implementing some mechanism for default values is a good idea. One reason is that this is possible just in TypeScript classes and not in interfaces. Second reason is that it would be some non-standard mechanism.

There would be possibility to instantiate the class and read default values from it but I think that in general it is bad idea to instantiate user classes during build because it can potentially run any code and is unexpected.
