### ISSUE TITLE
Better support for polymorphic DTOs

### ISSUE THREAD

**Issue by punya** [vojtechhabarta/typescript-generator#26]
Jackson supports [polymorphic (de)serialization](http://wiki.fasterxml.com/JacksonPolymorphicDeserialization). It would be cool if we could generate [user-defined type guards](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#user-defined-type-guard-functions) so that typescript code could do the same type dispatch that happens on the Java side. Concretely, say I have

```java
@JsonTypeInfo(use = Id.NAME, include = As.PROPERTY, property = "type")
@JsonSubTypes(@Type(CartesianPoint.class), @Type(PolarPoint.class))
interface Point {}

@JsonTypeName("cartesian")
class CartesianPoint implements Point {
  double x, y;
}

@JsonTypeName("polar")
class PolarPoint implements Point {
  double r, theta;
}
```

Currently we generate (roughly)

```ts
interface Point {}
interface CartesianPoint {
  x: number;
  y: number;
}
interface PolarPoint {
  r: number;
  theta: number;
}
```

It would be nice to have

```ts
interface Point {
  type: string;
}
interface CartesianPoint extends Point {
  x: number;
  y: number;
}
interface PolarPoint extends Point {
  r: number;
  theta: number;
}

function isCartesian(p: Point): p is CartesianPoint {
  return p.type === "cartesian";
}
function isPolar(p: Point): p is PolarPoint {
  return p.type === "polar";
}
```

**Comment by vojtechhabarta** [comment]
@punya sorry for late response, your suggestion is a good idea however there are some issues with it:
1. typescript-generator currently generates *declaration files* (`.d.ts`) which guarantees that user doesn't need to compile generated output and load it in the runtime.
2. Next thing is that handling Jackson's support for polymorphism is very specific.

To solve first point (and still preserve current behaviour) I am adding option for switching output format from *declaration file* (`.d.ts`) to *implementation file* (`.ts`). Default value is *declaration file* and user will need to set it to *implementation file* in order to allow runnable code to be generated.

Secondly I think that such specific feature should not be part of typescript-generator "core". So I am adding possibility to create emitter extensions which could write additional TypeScript code to output file. First extension will be extension for Jackson polymorphism and will be part of typescript-generator.

**Comment by punya** [comment]
Thanks @vojtechhabarta, that sounds like a great solution that balances keeping the core clean with providing the necessary functionality!

**Comment by vojtechhabarta** [comment]
I implemented emitter extensibility and `TypeGuardsForJackson2PolymorphismExtension` extension. It generates type guard functions such is:
``` TypeScript
function isCartesianPoint(point: Point): point is CartesianPoint {
    return point.type === "cartesian";
}
```
but there is missing `extends` clause in the output if base type is interface:
``` TypeScript
interface CartesianPoint {
    x: number;
    y: number;
}
```
This is because typescript-generator in general doesn't support inheritance from interfaces. As a result of this limitation it was also needed to generate `@JsonTypeInfo` property as optional:
``` TypeScript
interface Point {
    type?: string;
}
```

**Comment by vojtechhabarta** [comment]
Commit 0396ba09896d3a5b53eb7159076bf5883ca886ac adds support for modules and namespaces in implementation files (.ts). All supported combinations are marked in [Modules and Namespaces](http://vojtechhabarta.github.io/typescript-generator/doc/ModulesAndNamespaces.html) table (see right column).

**Comment by vojtechhabarta** [comment]
[Version 1.6.171](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v1.6.171) completes support for modules and namespaces in implementation files (`.ts`).

**Comment by vojtechhabarta** [comment]
Interface inheritance (#36) is implemented. I also removed optionality of `@JsonTypeInfo` property.
