### ISSUE TITLE
Support different typescript module output types, not only UMD

### ISSUE THREAD

**Issue by mzuzcak** [vojtechhabarta/typescript-generator#279]
typescript compiler generates files with UMD module type setting. this type is not usable in webpack. could you add support for different module types, such as commonjs?

**Comment by vojtechhabarta** [comment]
More info:
When generating TypeScript implementation file (.ts) and also NPM `package.json` there is a `build` script which (when run by user) is supposed to invoke TypeScript compiler and produce JavaScript file. This `build` script has hardcoded value `tsc --module umd --moduleResolution node --target es5 --lib es6 --declaration --sourceMap $outputFile`. This requirement is to allow to change `--module` parameter in this one-line script.

Solution:
I think somebody would need to change other parameters as well. Or somebody would want to just pass `tsconfig.json` file instead of all these parameters. So I added `npmBuildScript` parameter which allows to specify whole command at once. This is slightly more verbose when you only need to change one parameter but is flexible without adding more and more parameters.

**Comment by vojtechhabarta** [comment]
Released in [v2.8.449](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.8.449).
