### ISSUE TITLE
Either<A,B> translate to A | B

### ISSUE THREAD

**Issue by abersnaze** [vojtechhabarta/typescript-generator#286]
I was wondering if there is support scala.util.Either type? Is there some way to plug in support for it?

**Comment by vojtechhabarta** [comment]
`scala.util.Either` is not currently supported.

What exactly is your use case?

I tried to serialize `Either` values using Jackson with `DefaultScalaModule`. Following Java code:
``` java
List<Either<String, Number>> list = Arrays.asList(
        new Left<>("test"),
        new Right<>(42)
);
ObjectMapper objectMapper = new ObjectMapper();
objectMapper.registerModule(new DefaultScalaModule());
System.out.println(objectMapper.writeValueAsString(list));
```
produces this output:
``` json
[
    {
        "l": "test"
    },
    {
        "r": 42
    }
]
```

So instead of translating Either<A, B>> to just `A | B` we would need to translate it to something like this:
``` typescript
type Either<L, R> = {
    "l": L;
    "r"?: undefined;
} | {
    "l"?: undefined;
    "r": R;
}
```

BTW are you aware of [Tagged unions](https://github.com/vojtechhabarta/typescript-generator/pull/81) - another form of disjoint unions - which uses some discriminant property and is well supported in Jackson, typescript-generator and TypeScript itself?

**Comment by abersnaze** [comment]
The tagged unions look like a better options because of the discriminant.
