### ISSUE TITLE
Non-deterministic output of typescript model

### ISSUE THREAD

**Issue by pkozelka** [vojtechhabarta/typescript-generator#335]
The ordering of class fields in resulting `.ts` code is nearly deterministic, except for one case:
when the java model class contains *both* _fields_ and _getters_.

It still generates correct output, but different with each execution.

In my use-case, where we use the generated code also for detecting (and preventing) unintended changes to the REST model, this is a bit annoying.
The easiest workaround on our side would be to fix the "mixed" situation, but it's actually not so easy (due to organizational limitations).
And maybe you would prefer to have the generator completely deterministic, am I right?

**Comment by vojtechhabarta** [comment]
Hi Petr,

Ideally I would like to have both _deterministic_ order AND some _logical_ order (as in source code).

I assume you are using Jackson library. In this case typescript-generator uses Jackson's `BeanSerializer` to get list of properties of some bean. Since Java reflection API doesn't return methods (getters) in source code order Jackson has some ways how to influence order of properties. You can use for example `@JsonPropertyOrder` annotation.

But I think for your use case typescript-generator has `sortDeclarations` parameter which sorts properties alphabetically.

**Comment by pkozelka** [comment]
@vojtechhabarta thanks, this helped! I don't see how I could miss this one, but - perfect!
