### ISSUE TITLE
Consider @Produces({MediaType.TEXT_PLAIN}) for "generateJaxrsApplicationClient"

### ISSUE THREAD

**Issue by stenzengel** [vojtechhabarta/typescript-generator#351]
Thank you very much for your helpful project. Generating client classes works well for most cases, but in very rare cases, our Java-Code produces plain text responses:

Example:
```java
@GET
@Path("/")
@Produces({MediaType.TEXT_PLAIN})
public String myMethod()
```

In this case, I have to change a parameter value (from "json" to "text") when calling the client we use (the Angular "HttpClient"). This is done in our adapter class which implements the typescript-generator's "HttpClient" interface. My current problem is, that I cannot find a way to retrieve the "MediaType" of the response at this place. 

The generator's interface is:
```typescript
export interface HttpClient {
    request<R>(requestConfig: { method: string; url: string; queryParams?: any; data?: any; copyFn?: (data: R) => R; }): RestResponse<R>;
}
```

Is there a way to find the "MediaType"?

**Comment by vojtechhabarta** [comment]
Currently there is no "MediaType" parameter. But I think you could do it differently.

Instead of passing _expected_ media type to Angular HttpClient using `responseType` parameter you could check what you have actually _received_ in the response object. To get response object instead of JSON data you can use `observe: "response"` parameter. Then you can get response headers, check the `Content-Type` and process response body as needed (you need to parse JSON yourself before returning it from `request` function).

I found this possibility here: https://github.com/angular/angular/issues/22794#issuecomment-373709374.

**Comment by stenzengel** [comment]
Thank you! That should work.

**Comment by w0wka91** [comment]
Did this work for you @stenzengel ?

**Comment by stenzengel** [comment]
@w0wka91 Yes, this worked for me. But I can't remember what I actually implemented, and I don't work in that project anymore.
