### ISSUE TITLE
Set indent size

### ISSUE THREAD

**Issue by Raak** [vojtechhabarta/typescript-generator#363]
Hello,

I have an issue with either of the two indent-settings. Our Codestyle is set to 2 spaces so it would be nice to make the generated .d.ts file compliant with this, however it always generated 4 spaces for an indent.
What I have tried:
```
<indentString>  </indentString>
<indentString>&#160;&#160;</indentString>
```

I also saw that there is a non-documented (at least [here](http://www.habarta.cz/typescript-generator/maven/typescript-generator-maven-plugin/generate-mojo.html#indentString)) property named `<indentSize>`, however I couldn't figure out what this did because changing this seemingly did nothing. 

I'm not sure if this is a bug or if I'm missing something, but either way help would be greatly appreciated.

Thanks!

**Comment by vojtechhabarta** [comment]
There is nothing like `indentSize` in typescript-generator.

I tried
``` xml
<indentString>  </indentString>
```
and indeed this didn't work because XML parser removed whitespaces.

Solution I found is:
``` xml
<indentString xml:space="preserve">  </indentString>
```

It is really tricky so I added this to documentation: [indentString](http://www.habarta.cz/typescript-generator/maven/typescript-generator-maven-plugin/generate-mojo.html#indentString).

**Comment by Raak** [comment]
Ah yes, that did the trick!
Thanks a lot for that quick reply
