### ISSUE TITLE
Generate Class in different ts file with the Package Structure

### ISSUE THREAD

**Issue by mouldiOuni** [vojtechhabarta/typescript-generator#371]
It would be so nice if the Generated TS classes can be in different declaration files and creating the folders (packages) structure like the Java Structure. It is great for classes with Java Classes with the same names but in different Packages.

**Comment by vojtechhabarta** [comment]
I don't want to generate multiple declaration files because it would complicate typescript-generator and its usage (there are some variants how to split output into files and directories).

For Java classes with the same name it is possible to use [customTypeNaming](http://www.habarta.cz/typescript-generator/maven/typescript-generator-maven-plugin/generate-mojo.html#customTypeNaming) parameter and specify needed TypeScript names.

If you want to retain Java package structure in TypeScript you can use [mapPackagesToNamespaces](http://www.habarta.cz/typescript-generator/maven/typescript-generator-maven-plugin/generate-mojo.html#mapPackagesToNamespaces) parameter which will generate TypeScript namespace for each Java package (but the output will still be in one file).
