### ISSUE TITLE
Issue with Hashmap Conversion

### ISSUE THREAD

**Issue by gotwig** [vojtechhabarta/typescript-generator#385]
Hello,

this Java code:
`   private Map<Integer, CustomDto1> data1 = new HashMap<>();`
    `private HashMap<Integer, CustomDto2> data2; `

results in this typescript code:
` data1: { [index: string]: CustomDto1 };
  data2: { [index: string]: CustomDto2 };`

Im wondering why the result is not a number index, but instead a string?

Can someone help me to understand this?

Thank you.

**Comment by vojtechhabarta** [comment]
Hello,

keys in JSON are strings. When you write your `data1` and `data2` to JSON using Jackson then keys will be converted to strings.  You can also try following code:
``` java
System.out.println(new ObjectMapper().writeValueAsString(Collections.singletonMap(42, "text")));
```
output is:
``` json
{"42":"text"}
```

**Comment by gotwig** [comment]
Hello Vojtěch,

thank you for the quick reply.

Indeed, JSON index are probably not possible.

However, I am talking about the typescript kind of things - this is independent of the runtime javascript.

What im saying is, why does 
`private HashMap<Integer, CustomDto2> data2;`

not convert to
`data2: { [index: number]: CustomDto2 };`
? because when im changing it by hand, I see no problems with my IDE or the typescript compiler.

I think this is an error of the typescript-generator, can you help me to fix it?

**Comment by vojtechhabarta** [comment]
Purpose of Jackson is to write valid JSON so that's why it converts maps keys to strings.

Purpose of typescript-generator (when `jsonLibrary` parameter is set to `jackson2`) is to generate declarations that describe JSON data generated by Jackson library. This works correctly in this case.

What typescript-generator doesn't do (and what you probably want) is to transform general Java code to TypeScript. I don't know how you can achieve this (currently it is not possible in typescript-generator). How you want to use this generated code? Not for sending and receiving JSON data?

**Comment by gotwig** [comment]
I want to use the declartions with JSON code, thats right :) 

Thanks for explaining! Im not sure if we leave this ticket open or not.. :D

**Comment by vojtechhabarta** [comment]
From my perspective (repository owner) closed issue is better than opened issue 😏

**Comment by vojtechhabarta** [comment]
Closing the issue 🙂
