### ISSUE TITLE
Use org.slf4j.Logger instead of custom

### ISSUE THREAD

**Issue by SButterfly** [vojtechhabarta/typescript-generator#425]
Hello
Could you use [org.slf4j.logger](http://www.slf4j.org/apidocs/org/slf4j/Logger.html) logger instead of custom one?

**Comment by vojtechhabarta** [comment]
Hello,

If you are running typescript-generator directly from Java you can subclass `cz.habarta.typescript.generator.Logger`, override `write` method and delegate it to SLF4J.
You can then set your custom `Logger` using `cz.habarta.typescript.generator.TypeScriptGenerator.setLogger()` method.

Is this what you wanted?

**Comment by SButterfly** [comment]
Yes! Thank you.
But why not to use already existing logger?

**Comment by vojtechhabarta** [comment]
Logging in typescript-generator is rather simple so it's not worth using any complex logging framework.

Moreover it would rise a question which framework to use. I would use `java.util.logging` because it is part of Java but this would start issues how to configure it in different environments and how to integrate it with other logging frameworks.
