### ISSUE TITLE
Merging JAX-Rs and Spring functionality

### ISSUE THREAD

**Issue by RobbinBaauw** [vojtechhabarta/typescript-generator#437]
Hi,

This library has excellent JAX-Rs support, while I found that there are more problems when using Spring (e.g. resolving generics and more). I was wondering why this is, as it seems to me that both ways of REST controllers are pretty similar, though with a bit different annotation names and ways of using them.

You said in another issue that:
> Generics are resolved differently for JAX-RS and Spring - JAX-RS is resolved by typescript-generator itself while Spring is resolved using Spring libraries.

But can't we change that? It seems to me that the JAX-Rs parser can be mostly reused for Spring as well, while adding specifics for both in the subclass for the respective library (e.g. Pageable for Spring).

Maybe I'm completely wrong, but in my view it would help in a way that a fix or improvement would improve both Spring and JAX-Rs instead of just a single one.

If help is needed I'm willing to help :) If this seems like a possible idea I can create a POC.

**Comment by vojtechhabarta** [comment]
Hi,

support for JAX-RS is better than for Spring because it has been implement longer time ago and was incrementally improved.

I don't think it is practical to create common parser and subclasses for these technologies because there are relatively big differences like annotation "inheritance", sub-resources etc. And I think for Spring we can leverage it's own utility classes like `GenericTypeResolver`, `AnnotationUtils` and `AnnotatedElementUtils` so we can get closer to Spring behavior. We can of course share also some code between JAX-RS and Spring support but instead of subclassing we can have utility classes like `Utils`, `GenericsResolver` etc.

I think improving Spring support is now about identifying cases where typescript-generator does not behave exactly as Spring and fixing these cases which would be the same work regardless we have common superclass or not.

**Comment by RobbinBaauw** [comment]
Right!

After exams I will try and fix the issues I have with Spring :)
