### ISSUE TITLE
Javadoc transfer doesn't transfer javadoc tags

### ISSUE THREAD

**Issue by tjwilson90** [vojtechhabarta/typescript-generator#44]
E.g., @param and @return. These tags are frequently the bulk, if not the entirety, of a javadoc comment.

**Comment by vojtechhabarta** [comment]
I think only `@return` is useful on properties defined by getter method. Or do you have any example for `@param`?

**Comment by tjwilson90** [comment]
Ah, param is possibly not relevant to you (I generate ts interfaces for jaxrs resources with param annotations). The return tag would definitely be useful, but I don't really see why you wouldn't want to just transfer all tags.

**Comment by vojtechhabarta** [comment]
OK, but how do we format these tags?

According to http://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html#CHDBEFIF block tags are:
`@author` _name-text_
`@deprecated` _deprecated-text_
`@exception` _class-name_ _description_
`@param` _parameter-name_ _description_
`@return` _description_
`@see` _reference_
`@serial` _field-description_ | include | exclude
`@serialData` _data-description_
`@serialField` _field-name_ _field-type_ _field-description_
`@since` _since-text_
`@throws` _class-name_ _description_
`@version` _version-text_
and custom tags

XML Javadoc API gives us `TagInfo` object with `name` and `text` properties. For example for this line
```
* @param param1 description for param1
```
we get:
name = `"@param"`
text = `"param1 description for param1"`

Some options what we could write to output are:
- Transfer just `text` but this will look bad for some tags.
- Transfer tags as they are (for example `@param param1 description for param1`) but some tags (like `@param`, `@return`, `@throws`) does not make sense on TypeScript property. I am also not sure if all Javadoc tags are valid JSDoc tags.
- Reformat tags. Remove `@` character and make first letter uppercase. For example for `@since 1.1` generate `Since 1.1`. This looks relatively good for most tags but maybe we will want to take advantage of JSDoc tags for some more complicated cases in the future.

What do you think?

**Comment by tjwilson90** [comment]
Option 2 or 3 both work for me. It looks like all javadoc tags other than @serial, @serialData, and @serialField are valid tags in jsdoc, but as you mention they may not be entirely appropriate when moved from java properties to typescript fields. I'm not super concerned about that, interested mostly in just seeing that all the information gets transferred, even if it's not in the ideal format.

**Comment by vojtechhabarta** [comment]
Implemented option 2.
