### ISSUE TITLE
Spring in core

### ISSUE THREAD

**Issue by RobbinBaauw** [vojtechhabarta/typescript-generator#444]
Hi,

I have a question, why is Spring support a separate project? For the end user it would be much nicer if they didn't have to include a separate project for Spring.

**Comment by vojtechhabarta** [comment]
Hi, the reason is that Spring support adds more than 25 dependencies and I don't want to let people download half of the internet. And more importantly it could bring version conflicts. It would be terrible if people not using Spring could be affected for example by Spring (and its dependencies) update.

**Comment by RobbinBaauw** [comment]
Hm okay, seems reasonable. Maybe it would be possible to make extra gradle and maven projects which do include Spring. That would make it easier for the end user, though maybe it's not very important.

**Comment by vojtechhabarta** [comment]
I've [added](https://github.com/vojtechhabarta/typescript-generator/commit/eed77a6dfb3a6bf5c5b12ab21ec39fbbd924345d) example to [README](https://github.com/vojtechhabarta/typescript-generator) which shows how to add Spring support in Maven.
