### ISSUE TITLE
Sorting of generated attributes is not stable

### ISSUE THREAD

**Issue by samuelstein** [vojtechhabarta/typescript-generator#449]
hi,
the lib is very nice but unfortunately the sorting of the generated attributes/properties is not stable and can change from time to time. i suggest a stable sorting so that the order will remain.

**Comment by vojtechhabarta** [comment]
For properties based on fields original source order is preserved but order of properties based on getters is not preserved because Java reflection doesn't return list of methods in source order.

Anyway you can set [sortDeclarations](http://www.habarta.cz/typescript-generator/maven/typescript-generator-maven-plugin/generate-mojo.html#sortDeclarations) parameter to `true` to sort properties alphabetically.

**Comment by samuelstein** [comment]
thanks for the fast reply. this i didn't knew.
