### ISSUE TITLE
Optional properties with primitive type

### ISSUE THREAD

**Issue by olegshtch** [vojtechhabarta/typescript-generator#457]
Is it possible to generate 
```typescript
interface A {
 f?: boolean;
}
```
from
```java
class A {
 public boolean f;
}
```
?

It's doesn't make sense to have a `@Nullable` here but maybe with some Jackson2 annotation allow to don't fill this field to left it default.

**Comment by vojtechhabarta** [comment]
Technically `@Nullable` annotation can be used also on properties with primitive type but since it is weird you could create an annotation with the name better describing the purpose, for example:
``` java
@Retention(RetentionPolicy.RUNTIME)
@interface NotRequired {
}
```
and add it to typescript-generator configuration parameter `optionalAnnotations`. To me following usage seems fine:
``` java
class A {
    @NotRequired
    public boolean f;
}
```
