### ISSUE TITLE
Extra property when inheriting generic

### ISSUE THREAD

**Issue by mistic100** [vojtechhabarta/typescript-generator#466]
I have this Java model :

```java
interface IIdentifiableEntity<ID extends Serializable> {
  ID getId();
}

interface IApplication extends IIdentifiableEntity<Long> {
  String getCode();
  String getNom();
}
```

The generated TS is :

```ts
export interface IIdentifiableEntity<ID> {
    id: ID;
}

export interface IApplication extends IIdentifiableEntity<number> {
    code: string;
    id: number; // extra property
    nom: string;
}
```

The generated `IApplication` re-declare the `id` property when it is not useful.

(note: I use a custom file generator bases on the generated model but I see that `TsBeanModel#properties` contains the `id` property for IApplication)

This is not critical be perhaps is worth investigating.

---

My configuration is :

```java
        Settings settings = new Settings();
        settings.classLoader = jarClassLoader;
        settings.outputKind = TypeScriptOutputKind.global;
        settings.jsonLibrary = JsonLibrary.jackson2;
        settings.mapClasses = ClassMapping.asClasses;
        settings.outputFileType = TypeScriptFileType.implementationFile;
        settings.mapDate = DateMapping.asDate;
        settings.mapPackagesToNamespaces = true;

        settings.customTypeMappings.put(LocalDateTime.class.getCanonicalName(), "Date");
        settings.customTypeMappings.put(Geometry.class.getCanonicalName(), "GeoJSON");
        settings.customTypeMappings.put(Stream.class.getCanonicalName()+"<T>", "Array[T]");

        Jackson2Configuration configuration = new Jackson2Configuration();
        configuration.enumsUsingToString = true;
        configuration.fieldVisibility = Visibility.DEFAULT;
        configuration.getterVisibility = Visibility.DEFAULT;
        configuration.isGetterVisibility = Visibility.DEFAULT;
        configuration.setterVisibility = Visibility.DEFAULT;
        configuration.creatorVisibility = Visibility.DEFAULT;
        settings.jackson2Configuration = Jackson2ConfigurationResolved.from(configuration, jarClassLoader);
        return settings;
```

**Comment by vojtechhabarta** [comment]
You are right the `id` property should not be generated again in inherited type but I will explain why currently it is.

Typescript-generator gets list of bean properties from Jackson library. This list contains all properties regardless they are inherited or not. So it then removes the inherited ones. But it only removes properties that have not only the same name but also the same type. That's because in some cases (discriminant property) it is needed to narrow the union type in inherited interface.

In the case with generics the type of `id` property is not the same (`ID` vs `number`) so it is not removed. To be honest I don't think it is so important to solve this case.

**Comment by mistic100** [comment]
Understood. That's what I though because I don't have any duplicate when the inherited property is not generic.

**Comment by mojo2012** [comment]
Unfortunately this is an TS error when using strict mode. It only is allowed when prefixing the property with the `declare` keyword.
Is there any chance to find a better solution than the current one?
