### ISSUE TITLE
JsonTypeInfo with defaultImpl is generated as required property

### ISSUE THREAD

**Issue by danielkaneider** [vojtechhabarta/typescript-generator#480]
Jackson allows to specify a `JsonTypeInfo.defaultImpl` on an interface. If such annotation is present, the client doesn't need to specify `@class`/`@type` in the JSON object when pushing data.

Therefore, it would also be expected that the TS generates such property as optional, in the case a `defaultImpl` was specified.

**Comment by vojtechhabarta** [comment]
I tried it, here is my example:
``` java
@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME,
    include = JsonTypeInfo.As.PROPERTY,
    property = "type",
    defaultImpl = MyClass1.class)
@JsonSubTypes({
    @JsonSubTypes.Type(value = MyClass1.class, name = "class1"),
    @JsonSubTypes.Type(value = MyClass2.class, name = "class2"),
})
interface MyInterface {
    public String getText();
}

class MyClass1 implements MyInterface {
    public String getText() {
        return "text1";
    }
}

class MyClass2 implements MyInterface {
    public String getText() {
        return "text2";
    }
}
```

When I deserialize JSON the discriminant property is really optional:
`new ObjectMapper().readValue("{}", MyInterface.class).getText()` returns `text1`.

But when instance of `MyInterface` implementation is serialized `type` property is always there:
`new ObjectMapper().writeValueAsString(new MyClass1())`
produces: `{"type":"class1","text":"text1"}`.

So in one direction `type` property can be undefined but in other direction it cannot be undefined. BTW this is not the first time when contract defined by one class is slightly different depending on the direction. I was thinking about some mechanism how to distinguish the direction and generate proper contract but it is complicated especially when single class is used in both directions.

I agree that it would be slightly better to generate this property as optional because it is easier in TypeScript to handle property marked as optional when it isn't than to handle required property when it isn't. But since none of these cases are 100% correct I would leave it as it is now because of backwards compatibility.

**Comment by olegshtch** [comment]
I suppose properties those type depends on direction could work with https://github.com/microsoft/TypeScript/issues/43662
