### ISSUE TITLE
allow to define a custom name for typescript-generator-info.json

### ISSUE THREAD

**Issue by jantimon** [vojtechhabarta/typescript-generator#500]
Would it be possible to add an option which allows setting a different file name for the generated meta information?

**Comment by vojtechhabarta** [comment]
I don't want to add parameters which are not necessary.
Do you have any specific reason to have different file name?

**Comment by jantimon** [comment]
we generating models with different configurations and different `classPatterns` into the same directory and this will cause `typescript-generator-info.json` to be overwritten

**Comment by vojtechhabarta** [comment]
So those files are in the same directory and depend on each other? And together they form single npm module?
Otherwise you could generate them into different directories. And move/rename them later in the build process if needed.
I would be interested in more details because I didn't anticipate generating multiple modules into the same directory. When `outputKind` parameter is `module` I expected one npm module to be generated and second time the generator is run different npm module in different directory is generated.

**Comment by jantimon** [comment]
Actually I use the json during post processing to add additional typings for creating mocked data.

E.g.:

```ts
export const createMockData = {
   'com.demo.foo.model' : (model: com.demo.foo.model) => model
}
```

That way I am able to wrap it around mocked data sets e.g.:

```
createMockData['com.demo.foo.model']({
   title: 'foo'
})
```

**Comment by vojtechhabarta** [comment]
So would you be able to use different sub-directory for each typescript-generator run and then process those sub-directories?

**Comment by jantimon** [comment]
Yes that should work too 👍

**Comment by vojtechhabarta** [comment]
So could I close this issue?
