### ISSUE TITLE
typescript generation should ignore kotlin companion objects 

### ISSUE THREAD

**Issue by icguy** [vojtechhabarta/typescript-generator#531]
kotlin class:

```kotlin
class SubTaskProgress(
    val status: SubTaskStatus,
    val percent: Int
) {
    companion object {
        val pending = SubTaskProgress(SubTaskStatus.PENDING, 0)
        fun progress(percent: Int) = SubTaskProgress(SubTaskStatus.RUNNING, percent)
        val finished = SubTaskProgress(SubTaskStatus.FINISHED, 100)
    }
}
```

generated output:

```typescript
export interface SubTaskProgress {
    status: SubTaskStatus;
    percent: number;
}

export interface Companion {
    pending: SubTaskProgress;
    finished: SubTaskProgress;
}
```

expected output:
the same without the Companion interface

**Comment by vojtechhabarta** [comment]
Sorry for late response.

How do you specify input classes? I guess you are using `classPatterns` parameter.

You can use `excludeClassPatterns` and exclude companion objects for example like this: `**$Companion`. It's not much user friendly but I think typescript-generator cannot ignore all such classes because there might be rare cases where someone has such class in Java or actually wants to generate TypeScript for Kotlin companion object.

**Comment by icguy** [comment]
No problem, thanks for getting back to me.

Your assumption was correct, we are using class patterns. The solution you provided works fine, but i would consider adding some kind of config to enable or disable code generation from companion objects. That's up to you to decide, in the meantime I'm happy with the workaround.

Please close the issue if you consider it resolved.

**Comment by vojtechhabarta** [comment]
I prefer not to add new configuration parameter so I at least improved [Class Names Glob Patterns](https://github.com/vojtechhabarta/typescript-generator/wiki/Class-Names-Glob-Patterns/_compare/68931904f6b3eb79db2435be906fb287a58799a3...a5fc1ef9435c4073a2105a54127ea55d5d7b7bac) Wiki page. Hopefully users will be able to find this page using few keywords.
