### ISSUE TITLE
ClassNotFoundException when spring-boot-maven-plugin is used

### ISSUE THREAD

**Issue by mirza-ha** [vojtechhabarta/typescript-generator#576]
Hello.
First to say, I like your project very much, and it helped me for many other java projects.
I'm trying now to generate typescripts from spring boot project, and there is constantly ClassNotFoundException for classes that are regularly referenced and dependencies are added to my second microservice project where typescript-generator is set.

Even when I add pattern like <classPattern>com.xy.**Dto</classPattern>, class reference for some abcDto class is found, but then "java.lang.ClassNotFoundException: com.xy.abcDto" pops up.

I have noticed that when I exclude 
``` xml
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                 ...
```
 from spring boot project, classes are found, and typescript is generated.

And here is mine typescript-generator config:
``` xml
                <configuration>
                    <debug>false</debug>
                    <scanSpringApplication>true</scanSpringApplication>
                    <classPatterns>
                        <classPattern>com.xy.**Dto</classPattern>
                        <classPattern>com.xy.**Controller</classPattern>
                    </classPatterns>
                    <generateConstructors>false</generateConstructors>
                    <jsonLibrary>jackson2</jsonLibrary>
                    <outputKind>module</outputKind>
                    <restNamespacing>perResource</restNamespacing>
                    <outputFileType>implementationFile</outputFileType>
                    <outputFile>${project.basedir}/generated/app-rest.ts</outputFile>
                    <generateSpringApplicationClient>true</generateSpringApplicationClient>
                </configuration>
```

Is there some configuration that I'm missing?

**Comment by vojtechhabarta** [comment]
Hello,
I don't see any problem in your configuration.

There are two possibilities how to process Spring classes in typescript-generator. First is to set `scanSpringApplication` parameter to `true` and specify Spring Application class (using for example `classes` parameter). In this case specified application classes is loaded and list of controllers is obtained from it. Second is to leave `scanSpringApplication` parameter `false` and specify controllers using for example `classPatterns` or `classesWithAnnotations` parameters.

In your case I would try to remove `scanSpringApplication` parameter because loading Spring application is complex operation and could cause class loading issues. Could you also copy stacktrace or other relevant context?

**Comment by mirza-ha** [comment]
May be I was not clear in my description.
As you can see, scanSpringApplication=true is added to config, I tried without it also, result is always the same. classPattern filter is also there.

But one more important thing in my scenario is that I tried to reference microservices (for which I would like to generate ts) from my frontend maven config.
If I add typescript-generator directly to microservice pom (approach that I'm currently using), ts is generated. 
But what would like to do, is to reference all my microservices from single point, my frontend project, and generate ts in frontend project itself. In that case, strange behaviour that I described occurs. Classes are obviously somehow found with shown classPattern, but then error "java.lang.ClassNotFoundException: com.xy.abcDto" with exact class name occurs.

**Comment by vojtechhabarta** [comment]
Aha, ok. And how do you add your dependencies? If they are added to `<project>`/`<dependencies>` it should work normally.
And is problematic class included directly in specified dependency or is it included transitively?

**Comment by mirza-ha** [comment]
They are added as <project>/<dependencies> .
I tried with classes that are added directly in the dependency, but error occurs.

Another interesting thing is that, when the observed DTO class of referred microservice is in the separated module, it works, generator finds it and puts it to the generated TS. But if class is directly in the referred project (without modules), generator fails. So workaround that I'm currently using is to have separated modules containing DTOs in all my microservices projects.

**Comment by vojtechhabarta** [comment]
Are your services packaged as regular jar files (`<packaging>jar</packaging>` in pom.xml) or something else?
If jar, could you check if generated jar files have proper structure? Package structure should start in the root of the jar.

**Comment by imunic** [comment]
Experienced this issue today, the problem is how Spring Boot replaces the built artifact with the repackaged archive which has a different structure and cannot be used as a dependency of another project/module, the solutions is to add the `classifier` configuration option to the Spring Boot Maven plugin: https://docs.spring.io/spring-boot/docs/2.3.7.RELEASE/maven-plugin/reference/html/#goals-repackage-parameters-details-classifier Hope it helps.

**Comment by mirza-ha** [comment]
@vojtechhabarta It's packed as regular jar, and yes, I think that the problem is the structure that spring boot creates.
@imunic  I will try this workaround, thanks for advice.

**Comment by vojtechhabarta** [comment]
@mirza-ha hopefully you solved this issue somehow, @imunic thanks for sharing your findings
