### ISSUE TITLE
Parameters without the ModelAttribute annotation are not supported.

### ISSUE THREAD

**Issue by ilumer** [vojtechhabarta/typescript-generator#588]
for example
```
@RequestMapping("/greeting")
 public Response<Greeting> greeting(Greeting greeting) {
        return new Response<>(new Greeting(counter.incrementAndGet(), String.format(template,
                greeting.getContent())));
}
```

```java
public class Greeting {

    private final long id;
    private final String content;

    public Greeting(long id, String content) {
        this.id = id;
        this.content = content;
    }

    public long getId() {
        return id;
    }

    public String getContent() {
        return content;
    }
}
```
*.d.ts
```
greeting(options?: O): RestResponse<cz.habarta.typescript.generator.sample.spring.SpringTestApplication.Response<cz.habarta.typescript.generator.sample.spring.test.Greeting>> {
        return this.httpClient.request({ method: "GET", url: uriEncoding`/greeting`, options: options });
    }
```
the client lose the request param, maybe it is a bug for project(SpringApplicationParser not handle this situation). Although the api is not available from the official documentation, it is widely used and I hope you will consider adding this feature. sorry for my bad English
[Spring MVC: Complex object as GET @RequestParam](https://stackoverflow.com/questions/16942193/spring-mvc-complex-object-as-get-requestparam)

**Comment by ilumer** [comment]
Perhaps we can add a new parameter to replace the annotationNotRequired
```java
final ModelAttribute modelAttributeAnnotation = AnnotationUtils.findAnnotation(parameter, ModelAttribute.class);
if (modelAttributeAnnotation != null) {
}
```
spring mvc source code `ModelAttributeMethodProcessor` 
```
    public boolean supportsParameter(MethodParameter parameter) {
        return parameter.hasParameterAnnotation(ModelAttribute.class) || this.annotationNotRequired && !BeanUtils.isSimpleProperty(parameter.getParameterType());
    }
```

**Comment by vojtechhabarta** [comment]
Parameters without `@ModelAttribute` annotation are not supported because it would require to first implement all cases in table https://docs.spring.io/spring-framework/docs/current/reference/html/web.html#mvc-ann-arguments and then we could implement  last case "Any other argument" which you mentioned. It would require some work but more importantly it would be fragile. They could add some new cases in the future which could brake our implementation. So I would really prefer to support just explicitly recognized parameters and not "Any other argument" case.

Do you think you could add `@ModelAttribute` to your parameters like this?
``` java
@RequestMapping("/greeting")
public Greeting greeting(@ModelAttribute Greeting greeting) {
    return new Greeting();
}
```
This would generate following TypeScript declaration:
``` typescript
greeting(queryParams?: { content?: string; id?: number; }): RestResponse<Greeting>;
```
For this to work you would also need to change immutable class Greeting to POJO for example:
``` java
public static class Greeting {

    private long id;
    private String content;

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }
}
```

**Comment by ilumer** [comment]
Thanks for the reply, no `ModelAttribute` annoation was added because of the history of the project, thanks for solving my problem。
