### ISSUE TITLE
Non-deterministic output for Json Deserialization plugin despite sortDeclaration property enabled

### ISSUE THREAD

**Issue by kevincmanning** [vojtechhabarta/typescript-generator#600]
Getting a different order every time I run the build.

Here is a PR that defaults the initializers to sorted

**Comment by kevincmanning** [comment]
https://github.com/vojtechhabarta/typescript-generator/pull/601

**Comment by vojtechhabarta** [comment]
You are right that `JsonDeserializationExtension` doesn't respect `sortDeclarations` configuration parameter. And currently it's not possible to implement it because extensions don't have access to `Settings`.

But I think the goal for `JsonDeserializationExtension` should be to generate assignments in the same order as properties are declared. This order is sometimes non-deterministic (for example when defining properties using getters) and sometimes deterministic (for example when defining properties using fields).

So I moved sorting of bean properties to an earlier stage in the processing. This ensures that subsequent steps have properties in right order and can generate their declarations in correct order. This applies not only to `JsonDeserializationExtension` (and possibly to other extensions) but also to assignments in constructors (if `generateConstructors` parameter is used).

Could you please try it?

**Comment by vojtechhabarta** [comment]
Released in [v2.28.785](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.28.785).

**Comment by kevincmanning** [comment]
Thanks! I will try it tomorrow when I am back at work after the holidays.
