### ISSUE TITLE
Wrong property parsing

### ISSUE THREAD

**Issue by SButterfly** [vojtechhabarta/typescript-generator#617]
After some release my method

```java
public DisplaySeason setupSeason(Consumer<Season> seasonConsumer) {
        seasonConsumer.accept(season);
        return this;
}
```

was treated as property:

```ts
export interface DisplaySeason {
  ....
  upSeason: Consumer<Season>;
}
```

I temporary fix it by marking `@JsonIgnore`. Is there any better solution?

**Comment by vojtechhabarta** [comment]
Originally typescript-generator only used Jackson's `BeanSerializer` to get list of properties. But this list only contains properties that can be serialized, there can also be properties that can be deserialized. So starting from version 2.27 typescript-generator uses also `BeanDeserializer` to get list properties. This was added maily for #579.

The problem here is really curious. Obviously Jackson considers `setupSeason` method to be a setter for `upSeason` property which looks strange to me but we can see it using following sample code:
``` java
public static class DisplaySeason {
    private String value;
    public void setupSeason(String season) {
        value = season;
    }
}
public static void main(String[] args) throws JsonProcessingException {
    final ObjectMapper objectMapper = new ObjectMapper();
    final String json = "{\"upSeason\":\"abc\"}";
    final DisplaySeason displaySeason = objectMapper.readValue(json, DisplaySeason.class);
    System.out.println(displaySeason.value);
}
```
This code parses JSON, reads `upSeason` property, sets it using `setupSeason` method and prints `abc` value.

Apart from annotating `setupSeason` with `@JsonIgnore` you can also annotate `DisplaySeason` class with `@JsonAutoDetect(setterVisibility = JsonAutoDetect.Visibility.NONE)`.

**Comment by vojtechhabarta** [comment]
I realised that at least Jackson is consistent with Java Beans API. If I try following code:
``` java
BeanInfo beanInfo = Introspector.getBeanInfo(DisplaySeason.class);
Stream.of(beanInfo.getPropertyDescriptors()).forEach(System.out::println);
```
it also prints property `upSeason`.

**Comment by vojtechhabarta** [comment]
Actually there is one difference between Jackson and Java Beans. When method return type is `void` both consider this method a setter but when the return type is `DisplaySeason` only Jackson consider it a setter.

**Comment by vojtechhabarta** [comment]
Another possibility how to exclude setter methods is to configure `ObjectMapper` used by typescript-generator using `jackson2Configuration` parameter. Here is Gradle sample:
``` gradle
generateTypeScript {
    jsonLibrary = 'jackson2'
    jackson2Configuration = [
        setterVisibility: 'NONE'
    ]
}
```
