### ISSUE TITLE
error with maven plugin

### ISSUE THREAD

**Issue by ottopanini** [vojtechhabarta/typescript-generator#62]
Hi!

Cool useful tool you developed. 
I'm having a little problem with using the plugin with maven in eclipse. In my pom:
`
....

    <build>
        ...
        <plugins>
			<plugin>
			    <groupId>cz.habarta.typescript-generator</groupId>
			    <artifactId>typescript-generator-maven-plugin</artifactId>
			    <version>1.8.202</version>
			    <executions>
				    <execution>
			            <id>generate</id>
			            <goals>
			            	<goal>generate</goal>
			            </goals>
			            <configuration>
			                <jsonLibrary>jackson2</jsonLibrary>
					        <classPatterns>
			                    <pattern>com.syracos.domain.**</pattern>
			                </classPatterns>			                
			                <outputFile>target/rest.d.ts</outputFile>
			                <outputKind>global</outputKind>
			                <namespace>vos</namespace>
			            </configuration>
		            </execution>
			    </executions>
			</plugin>        
        </plugins>
    </build>
 ...
`
The ``<execution>` tag is marked as error in eclipse as long the goal "generate" is specified (with the other option "help" there are no errors). What is wrong with my configuration? Any hints? 
When I run maven install all seems to run as expected. There is some output at the log of your plugin processing:

[INFO] --- typescript-generator-maven-plugin:1.8.202:generate (generate) @ Syracos_MVN-java-api ---
Running TypeScriptGenerator version 1.8.202
Scanning classpath
Matched: 298, total: 29277.
Parsing 'com.syracos.domain.AbstractEntity'
Warning: Unknown serializer 'com.fasterxml.jackson.databind.ser.impl.UnknownSerializer' for class 'interface java.io.Serializable'
Warning: Unknown serializer 'com.fasterxml.jackson.databind.ser.impl.UnknownSerializer' for class 'interface java.io.Serializable'
Warning: Unknown serializer 'com.fasterxml.jackson.databind.ser.impl.UnknownSerializer' for class 'interface java.io.Serializable'
Parsing 'com.syracos.domain.AbstractEntity$AbstractEntityListener'
Warning: Unknown serializer 'com.fasterxml.jackson.databind.ser.impl.UnknownSerializer' for class 'class com.syracos.domain.AbstractEntity$AbstractEntityListener'
Parsing 'com.syracos.domain.Documentable'
....
and no error reported and yes there is also the expected output file. Maybe it's just an eclipse issue but anyhow thought you might be interested. 

Best regards and thanks 
Christian

**Comment by vojtechhabarta** [comment]
Hi Christian,

since output file was successfully generated I think there is nothing wrong with your configuration and nothing wrong with typescript-generator itself.

I haven't used eclipse for a long time so I downloaded latest version and tried to import Maven project with typescript-generator-maven-plugin. First I've got error
```
No marketplace entries found to handle typescript-generator-maven-plugin:1.7-SNAPSHOT:generate in Eclipse.  Please see Help for more information.
```
and when I opened pom.xml the `<execution>` element was marked with error
```
Plugin execution not covered by lifecycle configuration: cz.habarta.typescript-generator:typescript-generator-maven-plugin:1.7-SNAPSHOT:generate (execution: generate, phase: process-classes)
```
Typescript-generator-maven-plugin is by default bound to `process-classes` phase. When I overrode the phase to `package` by adding `<phase>package</phase>` element to this execution the error disappeared. It seems that eclipse is happy with some of the Maven phases only by default. Here is list of Maven phases: https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#Lifecycle_Reference but I don't know how these are handled by eclipse.

Thanks for using typescript-generator 😄 
Vojta

**Comment by vojtechhabarta** [comment]
BTW you can exclude `Serializable` interface from processing since it probably doesn't have any meaning for JSON data.
``` xml
<excludeClasses>
    <class>java.io.Serializable</class>
</excludeClasses>
```

**Comment by aparfeno** [comment]
Thank you very much for this utility!
I am trying to use it in a multi-module setting. I have a rather large multi-microservices project. I want to run your tool by default for all the modules, so I've added it to the parent pom.xml. And I've run into following issues:
1) Modules that do not have any eligible classes cause the failure (Input.java: 132). It would be great to have an option to make this situation a warning not a fatal error
2). In a given module I want to generate TS for only classes that are actually part of this module (compiled into target directory).  Instead it seems that generator uses the ClassLoader to find classes in included common jars. Since these common jars are included in multiple modules, I ended up with multiple *.t.ds files with the same content. Is there a way to restrict the class search to specific directory? Btw, I use classesWithAnnotations option to filter my classes.

Thank you in advance,
Alex
