### ISSUE TITLE
Incorrect typeInfo when using JsonSubTypes for same specific classes

### ISSUE THREAD

**Issue by danielkaneider** [vojtechhabarta/typescript-generator#635]
I've attached a unit test case with `JsonSubTypes` when using the same class (`SpecificType`) multiple times. I'm using the latest git version.
[JsonSubTypesTest.txt](https://github.com/vojtechhabarta/typescript-generator/files/5995566/JsonSubTypesTest.txt)

# Test case 1 (not working)
```
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "kind", include = JsonTypeInfo.As.PROPERTY)
@JsonSubTypes({
        @JsonSubTypes.Type(value = SpecificType.class, name = "TYPE_1"),
        @JsonSubTypes.Type(value = SpecificType.class, name = "TYPE_2"),
})
```

## Gives
```
export class ParentType {
    kind: "TYPE_1";
}

export class SpecificType extends ParentType {
    kind: "TYPE_1";
}

export type ParentTypeUnion = SpecificType;
```
# Test case 2 (working)
```
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "kind", include = JsonTypeInfo.As.PROPERTY)
@JsonSubTypes({
        @JsonSubTypes.Type(value = SpecificType2a.class, name = "TYPE_1"),
        @JsonSubTypes.Type(value = SpecificType2b.class, name = "TYPE_2"),
})
```

## Gives
```
Parsing 'cz.habarta.typescript.generator.JsonSubTypesTest$ParentType2'
Parsing 'cz.habarta.typescript.generator.JsonSubTypesTest$SpecificType2a'
Parsing 'cz.habarta.typescript.generator.JsonSubTypesTest$SpecificType2b'

export class ParentType2 {
    kind: "TYPE_1" | "TYPE_2";
}

export class SpecificType2a extends ParentType2 {
    kind: "TYPE_1";
}

export class SpecificType2b extends ParentType2 {
    kind: "TYPE_2";
}

export type ParentType2Union = SpecificType2a | SpecificType2b;
```

# Expectation
IMHO Also the first test case should include `TYPE_2` in the unions.

**Comment by vojtechhabarta** [comment]
Test case 1 is tricky situation. When Jackson is **serializing** JSON it uses only one type name (`TYPE_1`) but when it is **deserializing** JSON you are right, it uses both type names (`TYPE_1` and `TYPE_2`).

In 36696b76cfdd3741ebdba8503dca088a0e1a772e I refactored how those type names are determined. Previously whole processing was done by typescript-generator (annotations, class hierarchy, registered subtypes) but now typescript-generator uses Jackson's `TypeSerializer` and `SubtypeResolver` to get this information. So now the behavior matches Jackson more closely. Using this method it is also possible to get list of type names used for deserialization (`TYPE_1` and `TYPE_2`).

After mentioned refactoring in `Jackson2Parser` it would be relatively easy to introduce this feature (multiple type names for single class). I prototyped it in a [branch](https://github.com/vojtechhabarta/typescript-generator/commits/multiple-discriminant-literals) and also included your unit test. Downside is just few incompatible changes in model (because there are still no builders but all-args constructors). But to be honest I don't plan to merge it. The reason is that while generated classes describe contract better when sending JSON to Jackson they describe contract worse when receiving JSON from Jackson. Following example documents what could happen when processing JSON from Jackson in TypeScript:
``` typescript
declare const data: ParentTypeUnion;

switch (data.kind) {
    case "TYPE_1":
    case "TYPE_2":  // extra case which will never happen but without it compilation fails
        handleSpecificType(data);
        break;
    case "TYPE_3":
        handleSpecificType3(data);
        break;
    default:
        assertUnreachable(data);
}

function assertUnreachable(x: never): never {
    throw new Error("Didn't expect to get here");
}

declare function handleSpecificType(data: SpecificType): void;
declare function handleSpecificType3(data: SpecificType3): void;
```
There is an exhaustive switch statement which validates that all cases are handled so user must include also `TYPE_2` which will never happen. So generated contract would not be exactly correct and it could even break user's code.

In general the differences between serialization and deserialization are a big problem. I tried to solve part of this problem in #579 but those differences are on many more places.

**Comment by vojtechhabarta** [comment]
Mentioned commit is in [2.30.840](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.30.840) release.

**Comment by eivinsam** [comment]
Jackson2 behaves differently in this case:
```java
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.EXISTING_PROPERTY, property = "kind", visible = true)
/* class definition with member "String kind" */
```
Then the type is stored in the `kind`member and round-tripped perfectly. Which means that in that case the generated type ends up being wrong both for serialization and deserialization

**Comment by vojtechhabarta** [comment]
@eivinsam I am not sure about your comment. Kind value is round-tripped in Java object but discussed problem is how to deal with multiple kind values for one type.

I will close this issue as I think recent change is relatively good compromise between sending and receiving JSON data.

**Comment by olegshtch** [comment]
@vojtechhabarta For `JsonTypeInfo.As.EXISTING_PROPERTY` jackson2 use same value from property both for serialization and deserialization

**Comment by olegshtch** [comment]
Is branch `[multiple-discriminant-literals](https://github.com/vojtechhabarta/typescript-generator/compare/multiple-discriminant-literals)` still actual?
