### ISSUE TITLE
JsonIgnore not considered, when implementing Interface

### ISSUE THREAD

**Issue by thamacher** [vojtechhabarta/typescript-generator#67]
GIVEN:

public interface Formatable {
  @JsonProperty(value = "formatted", access = JsonProperty.Access.READ_ONLY)
  String toFormattedString();
}

public class FEDate implements Formatable {
 ......
  @JsonIgnore
  public String getFormatted() {
    return formatted;
  }
}

then the created TypeScript-definition still defines property "formatted" to be there, as it extends the TS-interface.

interface IDate extends IFormatable {
        date: Date;
 }
interface IFormatable {
        formatted: string;
}

I am not really sure, if this is really a bug or rather an conceptional error in the class structure. I just wanna raise it up, so maybe you also have an idea.

**Comment by vojtechhabarta** [comment]
I tried your case using this code:
``` java
public class TestIssue67 {

    public static void main(String[] args) throws Exception {
        final String output = new TypeScriptGenerator(TestUtils.settings()).generateTypeScript(Input.from(FEDate.class));
        System.out.println("=====");
        System.out.println(output);
        final String json = new ObjectMapper().writeValueAsString(new FEDate());
        System.out.println("=====");
        System.out.println(json);
    }


    public static interface Formatable {

        @JsonProperty(value = "formatted", access = JsonProperty.Access.READ_ONLY)
        String toFormattedString();
    }

    public static class FEDate implements Formatable {

        public String getDummy() {
            return "getDummy()";
        }

        @JsonIgnore
        public String getFormatted() {
            return "getFormatted()";
        }

        @Override
        public String toFormattedString() {
            return "toFormattedString()";
        }
    }

}
```
I have two notes:

1. There is really problem with class hierarchy. Property added in base class (or interface) cannot be removed in derived class (in OO languages like Java or TypeScript). You can use `@JsonIgnore` this way but then expect that TypeScript interface will not describe JSON data precisely.

2. There is a conflict in `formatted` property, it can be produced by two methods: `getFormatted()` and `toFormattedString()`. You must exclude both methods if you want `formatted` property to disappear.

**Comment by vojtechhabarta** [comment]
Closing the issue (inactive for some time). Please reopen if needed.

**Comment by ollwenjones** [comment]
I just ran into this same issue. Something is inheriting a method `getX()` from a super interface, but in the implementation the `getX()` method is annotated with `@jsonIgnore` so it is not in the generated JSON, but TypeScript is expecting it.

**Comment by vojtechhabarta** [comment]
Can you annotate `getX()` with `@JsonIgnore` in this super interface?
Or can you even exclude super interface using `excludeClasses` parameter?

**Comment by ollwenjones** [comment]
Since the main use case is generating TypeScript interfaces from a REST API, it seems to me the goal should be to accurately describe the REST JSON, not the Java class. Thus `@jsonIngore` should override class hierarchy.

One could argue that it doesn't harm anything to have _extra_ properties, but if UI developers are coding to a TypeScript interface, they are going to need confidence it accurately describes the JSON data, or else they'll have to be constantly referencing the Java classes anyway, and the TypeScript interface becomes much less useful.

I can also argue with my co-workers about why they added this interface just to `@jsonIgnore` its properties in the first place, but in the GWT project they are still able to use those methods after the JSON is deserialized. ☹️

**Comment by ollwenjones** [comment]
Sorry, I missed your reply.

> Can you annotate getX() with @JsonIgnore in this super interface?

Seems risky... since that super interface could be used in many places in a variety of ways.

> Or can you even exclude super interface using excludeClasses parameter?

I could test that out... I'm not sure what the result would be for the same reason.

**Comment by ollwenjones** [comment]
Adding @JsonIgnoreType on the class the getX() comes from had surprising (and seemingly unrelated) results in the generated TypeScript - other things were missing, but the .x was still inherited.

`excludeClasses` seemed to work but then we get a lot more generated TypeScript, which is okay, but we also lose the ability to code to that interface, which is very commonly used.

I understand the problem though as this class `implements SaidInterface` officially, but then doesn't provide some of it's parts? (because of JsonIgnore that isn't part of the type reflection.) I'll keep probing here as to why this pattern emerged. I suspect it's due to some classical inheritance hierarchy traps that unfortunately will just result in the TypeScript interfaces being less reliable for a time. ☹️

**Comment by vojtechhabarta** [comment]
I am thinking about this hierarchy:

- A (property `p`)
  - B
    - C
    - D
  - E
    - F (`@JsonIgnore` property `p`)
    - G

`A` contains property `p` and all descendants inherit it.

Let's say I add `@JsonIgnore` to `p` in `F`.
To model this case idea could be:
- remove `p` from `A`
- add `p` to all `E`'s siblings (`B` in this case)
- add `p` to all `F`'s siblings (`G` in this case)

Not only this is complicated but it is just not correct since `p` is now missing in `A`.
It also has disadvantage that shape of one class/interface depends on unrelated class/interface (in this case ignoring `p` in `F`  changes `B` and `G`.

If you cannot (or it doesn't make sense) remove `X` or whole super interface the **solution is probably to make property `X` optional** using some annotation like `javax.annotation.Nullable` or your own and configure it using `optionalAnnotations` parameter.

**Comment by ollwenjones** [comment]
> Not only this is complicated but it is just not correct since p is now missing in A.

I agree. I don't think this is a case to adjust the behavior of this plugin. 

Now imagine something like
```java
class H<I, J> implements K, L, M, N, O, P
```
- where `H` is a composite, and `I` probably also `implements K, L, M, N, O, P` and `J` very likely implements `L, O, P`. Thus `@JsonIgnore` was probably added to reduce generated JSON for data that is derivable in that chain. The only reason this was ever acceptable was because they had a deserializer on the client that knew how to make sense of it (for free) in GWT. Otherwise dealing with the JSON directly (like I'm doing now) would have made this approach unmaintainable really fast.

> the solution is probably to make property X optional

Thank you for that suggestion. I'll look into it, though I suspect this is kind of a systemic problem in this really large legacy product. 

Also, thanks again for your time.
