### ISSUE TITLE
Preserve Java Packages as Typescript Namespaces

### ISSUE THREAD

**Issue by girafi** [vojtechhabarta/typescript-generator#69]
In a large project with lots of JAXB-annotated classes, the typescript-generator soon fails because of collisions (Types with the same name.)
Typescript-generator reports many "Multiple classes are mapped to 'ObjectFactory' name."

In order to avoid this, i would find it helpful, if the generator would preserve the java packages and resemble them in a structure of nested namespaces in the TypeScript definition file.

An option `<createNamespacesFromPackageStructure>` or anything alike would be helpful.

Example:

2 Classes:
- com.me.Version
- com.you.Version

-> will report a collision error: "Multiple classes are mapped to 'Version' name.

With the proposed option, it would generate something like this:

    declare namespace com {
      namespace me {'
        interface Version {}
      }
      namespace you {
        interface Version {}
      }
    }

**Comment by vojtechhabarta** [comment]
This is not easy change because internally typescript-generator only works with simple names, not qualified names.

Workarounds are:
You can use `customTypeNaming` parameter to name conflicting classes yourself.
You can use `excludeClasses` to exclude classes you don't need.
If your application have two or more independent parts you can run typescript-generator for each part and produce declaration file for each part.

**Comment by girafi** [comment]
Thanks for the workaround suggestions @vojtechhabarta.
I understand that the current codebase does not support this.

**Comment by vojtechhabarta** [comment]
See release [1.24.314](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v1.24.314).
