### ISSUE TITLE
Can't process classes from another Maven project

### ISSUE THREAD

**Issue by ogerardin** [vojtechhabarta/typescript-generator#72]
Unless I've missed something, you can only generate interfaces for classes in your current maven project. If you have a maven module for the web service and a maven module for the front-end, ideally you shouldn't have to generate the TS interfaces when building the back-end, so you'd need a way to specify where to look for the Java classes as a parameter.

**Comment by vojtechhabarta** [comment]
Typescript-generator-maven-plugin uses standard Maven way for managing classpath which is `<dependency>` element.

I think you have two or three options:

1. Generate TypeScript declaration files in **service module**. Here you have classes on classpath, you probably also have java sources so you can even use Javadoc comments. I wouldn't have logical problem with this option because I consider declaration files as another form of service contract documentation. But I understand that you don't want "pollute" service module with frontend technologies.

2. Generate TypeScript declaration files in **frontend module**. Here you can use `<dependency>` element to add module with service classes to classpath. However you can argue that you don't want to "pollute" frontend module with service classes.

3. Create special module just for generating TypeScript declarations. Again here you can use `<dependency>` element.

If you use option 1. or 3. you can use `maven-assembly-plugin` to create zip archive with declaration file which you can unpack in frontend module using `maven-dependency-plugin` similarly as described for [unpacking XML Javadoc file](https://github.com/vojtechhabarta/typescript-generator/wiki/Javadoc#multi-module-setup).

**Comment by ogerardin** [comment]
Thanks for the feedback. Currently I am using option 1, which I used to consider "polluting" the service module, but thinking about it now you may be right that it's a form of service contract, probably even the most appropriate one since the service will be consumed as JSON. So I might as well leave it as it is.

Also if I can make a suggestion: it's not totally clear by reading the docs whether the generator needs to access the sources or just the compiled classes; maybe it should be made clear that it doesn't require source code access except if you want to use Javadoc.

**Comment by vojtechhabarta** [comment]
I added note to readme mentioning this (https://github.com/vojtechhabarta/typescript-generator/commit/1fe2eb66527e74d04f559dd9a6cfb75da8c78b6f).
